// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "stmnplibrary/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

// AddBook provides a mock function with given fields: ctx, data
func (_m *AdminRepository) AddBook(ctx context.Context, data *entity.BookData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.BookData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCategory provides a mock function with given fields: ctx, data
func (_m *AdminRepository) AddCategory(ctx context.Context, data entity.Category) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddConnections provides a mock function with given fields: ctx, data
func (_m *AdminRepository) AddConnections(ctx context.Context, data []entity.Connections) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddConnections")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Connections) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookId provides a mock function with given fields: ctx, isbn
func (_m *AdminRepository) GetBookId(ctx context.Context, isbn string) (int, error) {
	ret := _m.Called(ctx, isbn)

	if len(ret) == 0 {
		panic("no return value specified for GetBookId")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, isbn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, isbn)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isbn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLDDone provides a mock function with given fields: ctx, offset
func (_m *AdminRepository) GetLDDone(ctx context.Context, offset int) ([]entity.LoanData, error) {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLDDone")
	}

	var r0 []entity.LoanData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.LoanData, error)); ok {
		return rf(ctx, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.LoanData); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LoanData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLDDont provides a mock function with given fields: ctx, offset
func (_m *AdminRepository) GetLDDont(ctx context.Context, offset int) ([]entity.LoanData, error) {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLDDont")
	}

	var r0 []entity.LoanData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.LoanData, error)); ok {
		return rf(ctx, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.LoanData); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LoanData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoanData provides a mock function with given fields: ctx, offset
func (_m *AdminRepository) GetLoanData(ctx context.Context, offset int) ([]entity.LoanData, error) {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanData")
	}

	var r0 []entity.LoanData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.LoanData, error)); ok {
		return rf(ctx, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.LoanData); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LoanData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentId provides a mock function with given fields: ctx, studentName
func (_m *AdminRepository) GetStudentId(ctx context.Context, studentName string) (int, error) {
	ret := _m.Called(ctx, studentName)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentId")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, studentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, studentName)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, studentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentLoan provides a mock function with given fields: ctx, idUser, idBook
func (_m *AdminRepository) GetStudentLoan(ctx context.Context, idUser int, idBook int) (entity.LdUpdate, error) {
	ret := _m.Called(ctx, idUser, idBook)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentLoan")
	}

	var r0 entity.LdUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (entity.LdUpdate, error)); ok {
		return rf(ctx, idUser, idBook)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) entity.LdUpdate); ok {
		r0 = rf(ctx, idUser, idBook)
	} else {
		r0 = ret.Get(0).(entity.LdUpdate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, idUser, idBook)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisDel provides a mock function with given fields: ctx, key
func (_m *AdminRepository) RedisDel(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RedisDel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisGet provides a mock function with given fields: ctx, key
func (_m *AdminRepository) RedisGet(ctx context.Context, key string) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RedisGet")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisSETNX provides a mock function with given fields: ctx, key, value, ttl
func (_m *AdminRepository) RedisSETNX(ctx context.Context, key string, value string, ttl time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RedisSETNX")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return rf(ctx, key, value, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, key, value, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisSet provides a mock function with given fields: ctx, key, data, ttl
func (_m *AdminRepository) RedisSet(ctx context.Context, key string, data interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RedisSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMaxBook provides a mock function with given fields: ctx, id
func (_m *AdminRepository) UpdateMaxBook(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMaxBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStock provides a mock function with given fields: ctx, idBook
func (_m *AdminRepository) UpdateStock(ctx context.Context, idBook int) error {
	ret := _m.Called(ctx, idBook)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, idBook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTabLoan provides a mock function with given fields: ctx, idUser, idBook, sanctions, returnedAt
func (_m *AdminRepository) UpdateTabLoan(ctx context.Context, idUser int, idBook int, sanctions int64, returnedAt time.Time) error {
	ret := _m.Called(ctx, idUser, idBook, sanctions, returnedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTabLoan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int64, time.Time) error); ok {
		r0 = rf(ctx, idUser, idBook, sanctions, returnedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *AdminRepository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
