// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "stmnplibrary/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CheckLoan provides a mock function with given fields: ctx, idBook, idUser
func (_m *UserRepository) CheckLoan(ctx context.Context, idBook int, idUser int) error {
	ret := _m.Called(ctx, idBook, idUser)

	if len(ret) == 0 {
		panic("no return value specified for CheckLoan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, idBook, idUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateLoan provides a mock function with given fields: ctx, loanData
func (_m *UserRepository) CreateLoan(ctx context.Context, loanData entity.Loan) error {
	ret := _m.Called(ctx, loanData)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Loan) error); ok {
		r0 = rf(ctx, loanData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBooks provides a mock function with given fields: ctx, offset
func (_m *UserRepository) GetBooks(ctx context.Context, offset int) ([]entity.Book, error) {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.Book, error)); ok {
		return rf(ctx, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.Book); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooksByAuthor provides a mock function with given fields: ctx, author, offset
func (_m *UserRepository) GetBooksByAuthor(ctx context.Context, author string, offset int) ([]entity.Book, error) {
	ret := _m.Called(ctx, author, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthor")
	}

	var r0 []entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]entity.Book, error)); ok {
		return rf(ctx, author, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []entity.Book); ok {
		r0 = rf(ctx, author, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, author, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooksByCategory provides a mock function with given fields: ctx, category, offset
func (_m *UserRepository) GetBooksByCategory(ctx context.Context, category []string, offset int) ([]entity.Book, error) {
	ret := _m.Called(ctx, category, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByCategory")
	}

	var r0 []entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) ([]entity.Book, error)); ok {
		return rf(ctx, category, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) []entity.Book); ok {
		r0 = rf(ctx, category, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int) error); ok {
		r1 = rf(ctx, category, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNIS provides a mock function with given fields: ctx, nis
func (_m *UserRepository) GetNIS(ctx context.Context, nis int) error {
	ret := _m.Called(ctx, nis)

	if len(ret) == 0 {
		panic("no return value specified for GetNIS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, nis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RateLimiter provides a mock function with given fields: ctx, key
func (_m *UserRepository) RateLimiter(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RateLimiter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisDel provides a mock function with given fields: ctx, key
func (_m *UserRepository) RedisDel(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RedisDel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisGet provides a mock function with given fields: ctx, key
func (_m *UserRepository) RedisGet(ctx context.Context, key string) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RedisGet")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisHGetAll provides a mock function with given fields: ctx, key, dest
func (_m *UserRepository) RedisHGetAll(ctx context.Context, key string, dest interface{}) error {
	ret := _m.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for RedisHGetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisHSET provides a mock function with given fields: ctx, key, value
func (_m *UserRepository) RedisHSET(ctx context.Context, key string, value interface{}) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for RedisHSET")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisSet provides a mock function with given fields: ctx, key, data, ttl
func (_m *UserRepository) RedisSet(ctx context.Context, key string, data interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RedisSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisWp provides a mock function with given fields: ctx, fn
func (_m *UserRepository) RedisWp(ctx context.Context, fn func(context.Context) (interface{}, error)) (interface{}, error) {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RedisWp")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) (interface{}, error)) (interface{}, error)); ok {
		return rf(ctx, fn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) (interface{}, error)) interface{}); ok {
		r0 = rf(ctx, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, func(context.Context) (interface{}, error)) error); ok {
		r1 = rf(ctx, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisWtx provides a mock function with given fields: ctx, fn
func (_m *UserRepository) RedisWtx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RedisWtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisZR provides a mock function with given fields: ctx, key, start, stop
func (_m *UserRepository) RedisZR(ctx context.Context, key string, start int, stop int) ([]string, error) {
	ret := _m.Called(ctx, key, start, stop)

	if len(ret) == 0 {
		panic("no return value specified for RedisZR")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, error)); ok {
		return rf(ctx, key, start, stop)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = rf(ctx, key, start, stop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, key, start, stop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedisZS provides a mock function with given fields: ctx, key, score, member
func (_m *UserRepository) RedisZS(ctx context.Context, key string, score float64, member interface{}) error {
	ret := _m.Called(ctx, key, score, member)

	if len(ret) == 0 {
		panic("no return value specified for RedisZS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, interface{}) error); ok {
		r0 = rf(ctx, key, score, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, data
func (_m *UserRepository) Register(ctx context.Context, data *entity.Students) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Students) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBookStock provides a mock function with given fields: ctx, idBook
func (_m *UserRepository) UpdateBookStock(ctx context.Context, idBook int) error {
	ret := _m.Called(ctx, idBook)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, idBook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLimitLoan provides a mock function with given fields: ctx, id
func (_m *UserRepository) UpdateLimitLoan(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLimitLoan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithContext provides a mock function with given fields: ctx, fn
func (_m *UserRepository) WithContext(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
