// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/gin-gonic/gin"
	"stmnplibrary/controller/handler/admin"
	handler2 "stmnplibrary/controller/handler/auth"
	handler3 "stmnplibrary/controller/handler/user"
	"stmnplibrary/controller/postgres/config"
	config2 "stmnplibrary/controller/redis/config"
	"stmnplibrary/controller/repository/admin"
	repository2 "stmnplibrary/controller/repository/auth"
	repository3 "stmnplibrary/controller/repository/user"
	"stmnplibrary/controller/service/admin"
	service2 "stmnplibrary/controller/service/auth"
	service3 "stmnplibrary/controller/service/user"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, func(), error) {
	string2 := config.ProviderConnStr()
	db := config.Init(string2)
	context := config2.ProviderCTX()
	client := config2.ConnectRedis(context)
	adminRepository := repository.FnAdminRepository(db, client)
	adminService := service.FnAdminService(adminRepository)
	adminHandler := handler.FnAdminHandler(adminService)
	authRepository := repository2.FnAuthRepository(db, client)
	authService := service2.FnAuthService(authRepository)
	authHandler := handler2.FnAuthHandler(authService)
	userRepository := repository3.FnUserRepository(db, client)
	userService := service3.FnUserService(userRepository)
	userHandler := handler3.FnUserHandler(userService)
	engine := WireHandler(adminHandler, authHandler, userHandler, userService)
	return engine, func() {}, nil
}
